cooking/urls.py
from django.urls import path

from . import views


app_name = 'cooking'
urlpatterns = [
    path('', views.IndexView, name='index'),
    path('ingredient/', views.IngredientsView, name='ingredient'),
    path('makesoup/', views.MakeSoupView, name='makesoup'),
    path('makesoup/soupinfo/', views.soupinfo, name='soupinfo'),
    path('api/', views.api, name='api'),
    path('statistic/', views.statistic, name='statistic'),
    path('addstatistic/', views.addstatistic, name='addstatistic'),
    path('resetcookies/', views.resetcookies, name='resetcookies'),
    path('settings/', views.settings, name='settings'),
    path('register/', views.auth, name='auth'),
    path('login/', views.login, name='login'),
    path('register/redir/', views.auth_redir, name='auth-redirect'),
    path('login/redir/', views.login_redir, name='login-redirect'),
    path('exit/', views.exit, name='exit'),
    path('deletesoup/', views.deletesoup, name='deletesoup'),
    path('deletesoup1/', views.deletesoup1, name='deletesoup1'),
    path('complexsoup/', views.createcomplex, name='complexsoup'),
]

soup/urls.py
from django.contrib import admin
from django.urls import include, path
from cooking import views

urlpatterns = [
    path('cooking/', include('cooking.urls')),
    path('admin/', admin.site.urls),
    path('', views.main),
]

cooking/models.py
from django.db import models

# Create your models here.
class Ingredient(models.Model):
    ingredient_name = models.CharField(max_length=50)
    ingredient_description = models.CharField(max_length=300)
    ingredient_effect = models.CharField(max_length=20)
    ingredient_color = models.CharField(max_length=10)
    ingredient_weight = models.IntegerField()
    ingredient_coefficient = models.IntegerField()

    def __str__(self):
        return self.ingredient_name

    class Meta:
        verbose_name = "Ингредиент"
        verbose_name_plural = "Ингредиенты"
        db_table = 'soup_ingredient_info'   # Название таблички в БД


class UserInfo(models.Model):
    user_name = models.CharField(max_length=20)
    user_img = models.CharField(max_length=100)
    user_email = models.CharField(max_length=30)
    user_password = models.CharField(max_length=50)
    user_soup_list = models.CharField(max_length=300)
    user_secret = models.CharField(max_length=50, default=" ")

    def __str__(self):
        return self.user_name

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

cooking/views.py
from django.shortcuts import render

# Create your views here.
from .models import Ingredient
from .models import UserInfo
# from django.views import generic
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseServerError, HttpResponseRedirect
from django.conf import settings
import random
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.encoding import force_bytes
from ipaddress import ip_address, ip_network
import requests
import hmac
from hashlib import sha1
from django.contrib.auth.hashers import PBKDF2PasswordHasher
from django.utils.crypto import get_random_string
from django.contrib.auth.password_validation import MinimumLengthValidator, CommonPasswordValidator


def IndexView(request):
    if request.COOKIES.get('wasauthorised'):
        secret = request.COOKIES.get('wasauthorised')
        User = UserInfo.objects.get(user_secret=secret)
        UserName = User.user_name
        response = HttpResponse()

        if request.COOKIES.get('livetime'):
            time = int(request.COOKIES.get('livetime'))
            response.set_cookie('wasauthorised', secret, time)
        else:
            response.set_cookie('wasauthorised', secret, 1209600)

        if "," in User.user_soup_list:
            cookie = "."
            return render(request, 'cooking/index.html', {"cookie": cookie, 'username': UserName})
        else:
            return render(request, 'cooking/index.html', {'username': UserName})

    if request.COOKIES.get('usersoup'):
        cookie = "."
        return render(request, 'cooking/index.html', {"cookie": cookie})
    else:
        return render(request, 'cooking/index.html')


def IngredientsView(request):
    template_name = 'cooking/ingredients.html'

    ingredient_list = Ingredient.objects.all()
    if request.COOKIES.get('wasauthorised'):
        secret = request.COOKIES.get('wasauthorised')
        User = UserInfo.objects.get(user_secret=secret)
        UserName = User.user_name
        return render(request, template_name, {'ingredient_list': ingredient_list, 'username': UserName})

    return render(request, template_name, {'ingredient_list': ingredient_list})


def MakeSoupView(request):
    template_name = 'cooking/makesoup.html'

    ingredient_list = Ingredient.objects.all()
    if request.COOKIES.get('wasauthorised'):
        secret = request.COOKIES.get('wasauthorised')
        User = UserInfo.objects.get(user_secret=secret)
        UserName = User.user_name
        return render(request, template_name, {'ingredient_list': ingredient_list, 'username': UserName})

    return render(request, template_name, {'ingredient_list': ingredient_list})


def soupinfo(request):
    ingredient_1 = Ingredient.objects.get(pk=request.POST['ingredient1'])
    ingrEffect_1 = ingredient_1.ingredient_effect
    ingr1_color = ingredient_1.ingredient_color
    ingrWeight_1 = ingredient_1.ingredient_weight
    ingrCoeff_1 = ingredient_1.ingredient_coefficient
    count_1 = int(request.POST['count1'])

    ingredient_2 = Ingredient.objects.get(pk=request.POST['ingredient2'])
    ingrEffect_2 = ingredient_2.ingredient_effect
    ingr2_color = ingredient_2.ingredient_color
    ingrWeight_2 = ingredient_2.ingredient_weight
    ingrCoeff_2 = ingredient_2.ingredient_coefficient
    count_2 = int(request.POST['count2'])

    mass = ingrWeight_1 * count_1 + ingrWeight_2 * count_2 + 5

    if mass > 205 or mass < 25:

        error = 'Суп не удовлетворяет требованиям'
        return render(request, 'cooking/soupinfo.html', {'error_message': error})

    else:

        if mass <= 85:
            effectDuration = 20
        elif 85 < mass <= 145:
            effectDuration = 40
        else:
            effectDuration = 60

        Rarely = random.randint(1, 100)
        if Rarely <= 50:
            soupRarely = "Common"
            effectduration = effectDuration
            soupsteep = random.triangular(0.0001, 0.0129)
            soupsteep = round(soupsteep, 4)

        elif 50 < Rarely <= 75:
            soupRarely = "Rare"
            effectduration = effectDuration + int(round(effectDuration / 10))
            soupsteep = random.triangular(0.013, 0.026)
            soupsteep = round(soupsteep, 4)

        elif 75 < Rarely <= 87:
            soupRarely = "Epic"
            effectduration = effectDuration + int(round(effectDuration / 5))
            soupsteep = random.triangular(0.26, 0.1)
            soupsteep = round(soupsteep, 4)

        elif 87 < Rarely <= 94:
            soupRarely = "Legendary"
            effectduration = effectDuration + int(round(effectDuration / 2))
            soupsteep = random.triangular(0.101, 0.159)
            soupsteep = round(soupsteep, 4)

        elif 94 < Rarely < 100:
            soupRarely = "Ancient"
            effectduration = effectDuration + int(round(effectDuration / 4 * 3))
            soupsteep = random.triangular(0.16, 0.199)
            soupsteep = round(soupsteep, 4)

        else:
            soupRarely = "Divine"
            effectduration = effectDuration * 2
            soupsteep = random.triangular(0.2, 0.26)
            soupsteep = round(soupsteep, 4)

        EffectChance = random.randint(1, 6)

        if EffectChance < 6 and ingrCoeff_1 > ingrCoeff_2 and ingrWeight_2 * count_2 > 1.5 * ingrWeight_1 * count_1:
            soupEffect = ingrEffect_1 + ingrEffect_2
        elif EffectChance < 6 and ingrCoeff_1 < ingrCoeff_2 and ingrWeight_1 * count_1 > 1.5 * ingrWeight_2 * count_2:
            soupEffect = ingrEffect_1 + ingrEffect_2
        elif EffectChance < 6 and ingrCoeff_1 > ingrCoeff_2 and ingrWeight_2 * count_2 < 1.5 * ingrWeight_1 * count_1:
            soupEffect = ingrEffect_1
        else:
            soupEffect = ingrEffect_2

        ingredient1_mass = ingrWeight_1 * count_1
        ingredient2_mass = ingrWeight_2 * count_2
        ingrediens_mass = ingredient1_mass + ingredient2_mass

        R_1 = int(ingr1_color[0:2], 16) * ingredient1_mass
        G_1 = int(ingr1_color[2:4], 16) * ingredient1_mass
        B_1 = int(ingr1_color[4:], 16) * ingredient1_mass

        R_2 = int(ingr2_color[0:2], 16) * ingredient2_mass
        G_2 = int(ingr2_color[2:4], 16) * ingredient2_mass
        B_2 = int(ingr2_color[4:], 16) * ingredient2_mass

        if round((R_1 + R_2) / ingrediens_mass) <= 15:
            Soup_R = '0' + hex(round((R_1 + R_2) / ingrediens_mass))
        else:
            Soup_R = hex(round((R_1 + R_2) / ingrediens_mass))

        if round((G_1 + G_2) / ingrediens_mass) <= 15:
            Soup_G = '0' + hex(round((G_1 + G_2) / ingrediens_mass))
        else:
            Soup_G = hex(round((G_1 + G_2) / ingrediens_mass))

        if round((B_1 + B_2) / ingrediens_mass) <= 15:
            Soup_B = '0' + hex(round((B_1 + B_2) / ingrediens_mass))
        else:
            Soup_B = hex(round((B_1 + B_2) / ingrediens_mass))

        SoupColor = Soup_R + Soup_G + Soup_B
        SoupColor = SoupColor.replace("0x", "")

        statistic_save = "Сохранить результат"

        soupsteep = str(soupsteep)

        if request.COOKIES.get('wasauthorised'):
            secret = request.COOKIES.get('wasauthorised')
            User = UserInfo.objects.get(user_secret=secret)
            UserName = User.user_name
            return render(request, 'cooking/soupinfo.html', {'SoupColor': SoupColor,
                                                             'SoupDuration': effectduration,
                                                             'SoupRarely': soupRarely,
                                                             'SoupEffect': soupEffect,
                                                             'SoupWeight': mass,
                                                             'statisticSave': statistic_save,
                                                             'SoupSteep': soupsteep,
                                                             'username': UserName})

        return render(request, 'cooking/soupinfo.html', {'SoupColor': SoupColor,
                                                         'SoupDuration': effectduration,
                                                         'SoupRarely': soupRarely,
                                                         'SoupEffect': soupEffect,
                                                         'SoupWeight': mass,
                                                         'statisticSave': statistic,
                                                         'SoupSteep': soupsteep})


def addstatistic(request):
    if request.POST.get('livetime'):
        day = request.POST['livetime']
        time = int(day) * 24 * 60 * 60
        response = HttpResponseRedirect('/cooking/')
        response.set_cookie('livetime', str(time), time)
        return response

    else:
        if request.COOKIES.get('wasauthorised'):
            User = UserInfo.objects.get(user_secret=request.COOKIES.get('wasauthorised'))
            text = request.POST['statistic']
            try:
                request.POST['complex']
                User.user_soup_list = text
                User.save()
                response = HttpResponseRedirect('/cooking/')
                return response
            except:
                if "," in User.user_soup_list:
                    soup_list = User.user_soup_list
                    soup_list = soup_list.split(",")
                    soup_count = len(soup_list) / 6
                    if soup_count == 2:
                        del soup_list[0:6]
                        text = text.split(",")
                        soup_list = soup_list + text
                        soup_list = ",".join(soup_list)
                        User.user_soup_list = soup_list
                        User.save()

                    elif soup_count == 1:
                        text = text.split(",")
                        soup_list = soup_list + text

cooking/templates/cooking/auth.html
{% load static %}

<link rel="stylesheet" href="{% static 'cooking/style.css' %}">
<link rel="stylesheet" href="{% static 'cooking/style_auth.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8 />
        <title>Вход на сайт</title>

        <script>
            window.onload = function () {
                if (document.getElementById('UserError')) {
                    document.getElementById('UserError').style.color = 'red'
                    document.getElementById('name').style.borderColor = 'red'
                    document.getElementById('name-label').style.color = 'red'
                }
                if (document.getElementById('MinLengthError')) {
                    document.getElementById('MinLengthError').style.color = 'red'
                    document.getElementById('password').style.borderColor = 'red'
                    document.getElementById('password-label').style.color = 'red'
                }

                if (document.getElementById('CommonError')) {
                    document.getElementById('CommonError').style.color = 'red'
                    document.getElementById('password').style.borderColor = 'red'
                    document.getElementById('password-label').style.color = 'red'
                }
            }

        </script>
    </head>

    <body>

        <div class="main">
            {% if user_error %}
                <a id="UserError">{{user_error}}</a>
            {% endif %}

            {% if minlength_error %}
                <a id="MinLengthError">{{minlength_error}}</a>
            {% endif %}

            {% if common_error %}
                <a id="CommonError">{{common_error}}</a>
            {% endif %}

            <form action="{% url 'cooking:auth-redirect' %}" method="post">
            {% csrf_token %}
                <span id="block-label">Создать аккаунт</span><br>
                <span id="name-label">Имя пользователя</span>
                <input type="text" name="name" id="name" required><br>

                <span id="email-label">Электронная почта</span>
                <input type="email" name="email" id="email" required>

                <span id="password-label">Пароль:</span>
                <input type="password" name="password" id="password" required>
                <input type="submit" id="submit">

            </form>
            <a href="{% url 'cooking:login' %}">У меня уже есть аккаунт</a>
            <a href="{% url 'cooking:index' %}">Вернутья на главную</a>
        </div>
    </body>
</html>

cooking/templates/cooking/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cooking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking/style_index.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8 />
        <title>Рецепты супов</title>
    </head>

    <body>
        <header>

            <div id="logo">
                <a>SoupCookers</a>
            </div>


            <div id="account-name" class="account-info">
                {% if username %}
                <a href="{% url 'cooking:login' %}">{{username}}</a>
                {% else %}
                <a href="{% url 'cooking:login' %}">Войти в аккаунт</a>
                {% endif %}
            </div>
            <div id="account-img" class="account-info">
                <div id="img"></div>
            </div>


        </header>

        <div class="main-outer">
        <div class="main-inner">
            <a href="{% url 'cooking:ingredient' %}" class="redirect" >Список ингредиентов</a><br>
            <a href="{% url 'cooking:makesoup' %}" class="redirect" >Приготовить супъ</a><br>
            <a href="{% url 'cooking:settings' %}" class="redirect" >Настройки</a><br>

            {% if cookie %}
            <a href="{% url 'cooking:statistic' %}" class="redirect" >Просмотреть сохранённый суп</a><br>
            {% endif %}
        </div>
        </div>

    </body>
</html>

cooking/templates/cooking/login.html
{% load static %}

<link rel="stylesheet" href="{% static 'cooking/style.css' %}">
<link rel="stylesheet" href="{% static 'cooking/style_login.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8 />
        <title>Вход на сайт</title>

        <script>
            window.onload = function () {

                if (document.getElementById('PasswordError')) {
                    document.getElementById('PasswordError').style.color = 'red'
                    document.getElementById('password').style.borderColor = 'red'
                    document.getElementById('password-label').style.color = 'red'
                }
                if (document.getElementById('UserError')) {
                    document.getElementById('UserError').style.color = 'red'
                    document.getElementById('name').style.borderColor = 'red'
                    document.getElementById('name-label').style.color = 'red'
                }
            }

        </script>
    </head>

    <body>

        <div class="main">
             {% if user_error %}
                <a id="UserError">{{ user_error }}</a>
            {% endif %}

            {% if password_error %}
                <a id="PasswordError">{{ password_error }}</a>
            {% endif %}

            <form action="{% url 'cooking:login-redirect' %}" method="post">
            {% csrf_token %}
                <span id="block-label">Войти в аккаунт</span><br>
                <span id="name-label">Имя пользователя</span>
                <input type="text" name="name" id="name" required><br>

                <span id="password-label">Пароль:</span>
                <input type="password" name="password" id="password" required>
                <input type="submit" id="submit">

            </form>
            <a href="{% url 'cooking:auth' %}">У меня нет аккаунта</a>
            <a href="{% url 'cooking:index' %}">Вернутья на главную</a>
        </div>
    </body>
</html>

cooking/templates/cooking/makesoup.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cooking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking/style_makesoup.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8 />
        <title>Сделать супъ</title>
        <link rel="stylesheet" href="../../static/cooking/style.css">
    </head>

    <body>
        <header>

            <div id="logo">
                <a href="{% url 'cooking:index' %}">SoupCookers</a>
            </div>


            <div id="account-name" class="account-info">
                {% if username %}
                <a href="{% url 'cooking:login' %}">{{username}}</a>
                {% else %}
                <a href="{% url 'cooking:login' %}">Войти в аккаунт</a>
                {% endif %}
            </div>
            <div id="account-img" class="account-info">
                <div id="img"></div>
            </div>

        </header>

        <div class="main">
            <form action="{% url 'cooking:soupinfo' %}" method="post">
                <span id="ingredlabel1">Первый ингредиент</span>
                <span id="ingredlabel2">Второй ингредиент</span>
            {% csrf_token %}
                <select name="ingredient1" size="3" id="ingred1" required>
                {% for ingredient in ingredient_list %}
                    <option value="{{ ingredient.id }}">{{ingredient.ingredient_name}}</option>

                {% endfor %}
                </select>

                <select name="ingredient2" size="3" id="ingred2" required>
                {% for ingredient in ingredient_list %}
                    <option value="{{ ingredient.id }}">{{ingredient.ingredient_name}}</option>

                {% endfor %}
                </select><br>
                <span id="countlabel1">Кол-во I ингредиента</span>
                <span id="countlabel2">Кол-во II ингредиента</span>
                <input name="count1" type="number" min="1" value="1" placeholder="Кол-во I ингредиента" id="count1" required>
                <input name="count2" type="number" min="1" value="1" placeholder="Кол-во II ингредиента" id="count2" required>
                <input type="submit" name="soup" id="input-submit" value="Рассчитать характеристики">
            </form>
            <a href="/cooking" class="redirect_back" >Вернуться обратно</a>
        </div>
    </body>
</html>

cooking/templates/cooking/settings.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cooking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking/style_settings.css' %}">


<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8 />
        <title>Рецепты супов</title>
    </head>

    <body>
        <header>

            <div id="logo">
                <a href="{% url 'cooking:index' %}">SoupCookers</a>
            </div>


            <div id="account-name" class="account-info">
                {% if username %}
                <a href="{% url 'cooking:login' %}">{{username}}</a>
                {% else %}
                <a href="{% url 'cooking:login' %}">Войти в аккаунт</a>
                {% endif %}
            </div>
            <div id="account-img" class="account-info">
                <div id="img"></div>
            </div>

        </header>

        <div class="main">
            {% if soupsave == "exist" %}
                <a href="{% url 'cooking:resetcookies' %}">Сбросить сохрание супа</a><br><br>

            {% endif %}
            <div id="live-time" class="content">
                <span>Настройка времени жизни сохранений в днях (без изменения
                    этого параметра, ваше сохранение сбросится после
                    выключения браузера)</span><br><br>

                <form action="{% url 'cooking:addstatistic' %}" method="post">
                {% csrf_token %}

                    <input type="number" name="livetime" max="365" min="1" value="1" placeholder="Время жизни сохранения" required>
                    <input type="submit" value="Сохранить время жизни">

                </form>
            </div>
            {% if wasauthorised == "exist" %}
                <div id="auth-exit" class="content">
                    <a href="{% url 'cooking:exit' %}">Выйти из аккаунта</a>
                </div>

            {% endif %}
            <a href="{% url 'cooking:index' %}" class="redirect_back" >Вернуться обратно</a>
        </div>
    </body>
</html>

cooking/templates/cooking/soupinfo.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cooking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking/style_soupinfo.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8 />
        <title>Значения супа</title>
        <script>
            window.onload = function() {
                var soupcolor = document.getElementById("soupcolor").innerText;
                document.getElementById("soupcolor1").style.backgroundColor = soupcolor;
            };

        </script>
        <style>
            #lol{
                display: none;

            }

        </style>
    </head>

    <body>
        <header>

            <div id="logo">
                <a href="{% url 'cooking:index' %}">SoupCookers</a>
            </div>


            <div id="account-name" class="account-info">
                {% if username %}
                <a href="{% url 'cooking:login' %}">{{username}}</a>
                {% else %}
                <a href="{% url 'cooking:login' %}">Войти в аккаунт</a>
                {% endif %}
            </div>
            <div id="account-img" class="account-info">
                <div id="img"></div>
            </div>

        </header>

    {% if error_message %}
        <p>{{ error_message }}</p>
        <a href="{% url 'cooking:makesoup' %}" class="redirect_back" >Вернуться к созданию супа</a>

    {% else %}
        <div class="main">
            <a id="soupcolor">{{SoupColor}}</a>

            <a>Ваш супь: </a>
            <div id="soupcolor1"></div><br>

            <a>Эффект супа: {{SoupEffect}}</a><br>
            <a>Длительность эффектов супа: {{SoupDuration}} секунд</a><br>
            <a>Редкость супа: {{SoupRarely}}</a><br>
            <a>Масса супа: {{SoupWeight}}</a><br>
            <a>Крутизна супа: {{SoupSteep}}</a><br>

            {% if statisticSave %}
                <form action="{% url 'cooking:addstatistic' %}" method="post">
                {% csrf_token %}
                    <input name="statistic" id="lol" value="'{{SoupEffect}}', '{{SoupDuration}}', '{{SoupRarely}}', '{{SoupWeight}}', '{{SoupColor}}', '{{SoupSteep}}'"><br>
                    {% if lol %}
                        <input name='complex' style="display: none;" value="qqq">
                    {% endif %}
                    <input type="submit" id="input-submit" name="soup" value="Сохранить результат">
                </form>


            {% endif %}
            <a href="{% url 'cooking:index' %}" class="redirect_back" >Вернуться в начало</a>
        </div>
    {% endif %}
    </body>



</html>

cooking/templates/cooking/statistic.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cooking/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cooking/stylestatistic.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8 />
        <title>Значения супа</title>
        <script>
            window.onload = function() {
                var soupcolor = document.getElementById("soupcolor").innerText;
                document.getElementById("color").style.backgroundColor = soupcolor;

                var soupcolor = document.getElementById("soupcolor1").innerText;
                document.getElementById("color1").style.backgroundColor = soupcolor;
            };

        </script>

    </head>

    <body>
        <header>

            <div id="logo">
                <a href="{% url 'cooking:index' %}">SoupCookers</a>
            </div>


            <div id="account-name" class="account-info">
                {% if username %}
                <a href="{% url 'cooking:login' %}">{{username}}</a>
                {% else %}
                <a href="{% url 'cooking:login' %}">Войти в аккаунт</a>
                {% endif %}
            </div>
            <div id="account-img" class="account-info">
                <div id="img"></div>
            </div>

        </header>

    {% if error_message %}
        <p>{{ error_message }}</p>
        <a href="{% url 'cooking:index' %}">Вернуться в начало</a>

    {% else %}
        <div class="main">
            <div id="soup1">
                <a class="soupcolor" id="soupcolor">{{soupColor}}</a>

                <a>Цвет супа: </a>
                <div class="color" id="color"></div><br>

                <a>Эффект супа: {{soupEffect}}</a><br>
                <a>Длительность эффектов супа: {{effectDuration}} секунд</a><br>
                <a>Редкость супа: {{rarely}}</a><br>
                <a>Масса супа: {{soupWeight}}</a><br>
                <a>Крутизна супа: {{soupSteep}}</a><br><br>
            </div>

            <div id="auth-delete-soup" class="content">
                <a href="{% url 'cooking:deletesoup' %}">Удалить сохранение</a>
            </div>

        {% if soupColor1 %}
            <div id="soup2">
               <a class="soupcolor" id="soupcolor1">{{soupColor1}}</a>

                <a>Цвет супа: </a>
                <div class="color" id="color1"></div><br>

                <a>Эффект супа: {{soupEffect1}}</a><br>
                <a>Длительность эффектов супа: {{effectDuration1}} секунд</a><br>
                <a>Редкость супа: {{rarely1}}</a><br>
                <a>Масса супа: {{soupWeight1}}</a><br>
                <a>Крутизна супа: {{soupSteep1}}</a><br><br>
            </div>

            <div id="auth-delete-soup1" class="content">
                <a href="{% url 'cooking:deletesoup1' %}">Удалить сохранение</a>
            </div>

            <div>
                <a href="{% url 'cooking:complexsoup' %}" class="redirect">lol</a><br>
                <span style="color: red">ВНИМАНИЕ! Ваше старое сохранение будет уничтожено в любом случае!</span>
            </div><br><br>
        {% endif %}

            <a href="{% url 'cooking:index' %}" class="redirect_back" >Вернуться в начало</a>
        </div>

    {% endif %}
    </body>



</html>